-- MySQL Script generated by MySQL Workbench
-- di 28 mrt 2017 12:53:18 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema zoetermeer-vooruit
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `zoetermeer-vooruit` ;

-- -----------------------------------------------------
-- Schema zoetermeer-vooruit
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `zoetermeer-vooruit` DEFAULT CHARACTER SET utf8mb4 ;
USE `zoetermeer-vooruit` ;

-- -----------------------------------------------------
-- Table `zoetermeer-vooruit`.`quiz`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zoetermeer-vooruit`.`quiz` ;

CREATE TABLE IF NOT EXISTS `zoetermeer-vooruit`.`quiz` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(40) NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `closing_date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `open_date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `zoetermeer-vooruit`.`question`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zoetermeer-vooruit`.`question` ;

CREATE TABLE IF NOT EXISTS `zoetermeer-vooruit`.`question` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(40) NOT NULL,
  `quiz_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `quiz_id` (`quiz_id` ASC),
  CONSTRAINT `question_ibfk_1`
    FOREIGN KEY (`quiz_id`)
    REFERENCES `zoetermeer-vooruit`.`quiz` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `zoetermeer-vooruit`.`answer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zoetermeer-vooruit`.`answer` ;

CREATE TABLE IF NOT EXISTS `zoetermeer-vooruit`.`answer` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(60) NOT NULL,
  `question_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `question_id` (`question_id` ASC),
  CONSTRAINT `answer_ibfk_1`
    FOREIGN KEY (`question_id`)
    REFERENCES `zoetermeer-vooruit`.`question` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `zoetermeer-vooruit`.`migrations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zoetermeer-vooruit`.`migrations` ;

CREATE TABLE IF NOT EXISTS `zoetermeer-vooruit`.`migrations` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `migration` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `batch` INT(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `zoetermeer-vooruit`.`reply`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zoetermeer-vooruit`.`reply` ;

CREATE TABLE IF NOT EXISTS `zoetermeer-vooruit`.`reply` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `answer_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `answer_id` (`answer_id` ASC),
  CONSTRAINT `reply_ibfk_1`
    FOREIGN KEY (`answer_id`)
    REFERENCES `zoetermeer-vooruit`.`answer` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `zoetermeer-vooruit`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zoetermeer-vooruit`.`user` ;

CREATE TABLE IF NOT EXISTS `zoetermeer-vooruit`.`user` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `last_name` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `email` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `password` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `remember_token` VARCHAR(100) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `uuid` INT(15) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `zoetermeer-vooruit`.`user_question`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zoetermeer-vooruit`.`user_question` ;

CREATE TABLE IF NOT EXISTS `zoetermeer-vooruit`.`user_question` (
  `user_id` INT(10) UNSIGNED NOT NULL,
  `idquestion_id` INT(11) NOT NULL,
  INDEX `user_id` (`user_id` ASC),
  INDEX `idquestion_id` (`idquestion_id` ASC),
  CONSTRAINT `user_question_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `zoetermeer-vooruit`.`user` (`id`),
  CONSTRAINT `user_question_ibfk_2`
    FOREIGN KEY (`idquestion_id`)
    REFERENCES `zoetermeer-vooruit`.`question` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
